# Generated by Django 5.0.2 on 2024-05-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
        migrations.AddField(
            model_name='work',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='work',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cleaners.work')),
            ],
        ),
    ]
